### ISSUE TITLE
Why no `get_identifiers` ?

### ISSUE THREAD

**Issue by WebReflection** [JeffersGlass/mp-templates#1]
This comment left me wondering why it's not implemented:
https://github.com/JeffersGlass/mp-templates/blob/main/template/template.py#L119

**Comment by JeffersGlass** [comment]
The honest answer is that `get_indentifiers` (at least in CPython's implementation) relies on the regex library's `finditer` method, which [Micropython doesn't implement](https://docs.micropython.org/en/latest/library/re.html). Nor does it implement `findall` or similar. The WASM version doesn't even implement the `match.start/end/span` attributes, preventing a simple search-trim-repeat method... and deeper than that I didn't get to when I put this together last night.

You've given me an idea, though, let me try something.

**Comment by JeffersGlass** [comment]
@WebReflection  `get_identifiers` has been implemented. No te that there's some inefficiencies there compared to how CPython does it, due to the limitations above, but It works and passes CPython's tests for the same.
